all:
  hosts:
    server1:
      ansible_host: 192.168.220.198
      ansible_user: user
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_user: root
      ansible_become_pass: user
      ansible_ssh_key_path: /home/morozovms/.ssh/id_rsa.pub
